### ISSUE TITLE
Discrimination against non coop students 

### ISSUE THREAD

**Issue by msbukal** [yucombinator/coop-friendship#5]
Excuse u but I identify as a non coop student and therefore I don't have a stream (no stream pride) and therefore am offended by this app. There should be an option for non coop students (usually in class for fall and winter) to match with coop students too. Please fix this before I report you for discrimination against minorities.

**Comment by yucombinator** [comment]
Sorry for the undue stress this app has caused you. Unfortunately non-coop support is not on our current roadmap for the next release, but may I suggest switching to Laurier? It's a great workaround for non coops to find their kind there.
